# Generated by Django 3.0.8 on 2020-10-29 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201028_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_no_primary',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_no_secondary',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='city',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='contact_no_primary',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='contact_no_secondary',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='primary_pincode',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='state',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+99999999", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_email', models.EmailField(blank=True, max_length=255)),
                ('contact_no_primary', models.CharField(blank=True, max_length=13, unique=True)),
                ('contact_no_secondary', models.CharField(blank=True, max_length=13)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('primary_pincode', models.CharField(blank=True, max_length=6)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_email', models.EmailField(blank=True, max_length=255)),
                ('contact_no_primary', models.CharField(blank=True, max_length=13, unique=True)),
                ('contact_no_secondary', models.CharField(blank=True, max_length=13)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('primary_pincode', models.CharField(blank=True, max_length=6)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
            ],
        ),
    ]
