# Generated by Django 3.1.2 on 2020-11-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Vinayak', max_length=150),
            preserve_default=False,
        ),
    ]
