# Generated by Django 3.1.2 on 2020-12-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201121_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
