# Generated by Django 3.0.8 on 2020-10-31 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_registered', models.BooleanField()),
                ('is_gst_registered', models.BooleanField()),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('company_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='stores.CompanyType')),
            ],
        ),
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('favourite', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Popularity',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'StoreCategories',
            },
        ),
        migrations.CreateModel(
            name='StoreSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'StoreSubcategories',
            },
        ),
        migrations.CreateModel(
            name='StoreManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobileno', models.CharField(max_length=13)),
                ('emailid', models.EmailField(max_length=254)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('designation', models.ForeignKey(default='Manager', on_delete=django.db.models.deletion.SET_DEFAULT, to='stores.Designation')),
            ],
        ),
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.CharField(blank=True, max_length=50)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('nearest_landmark', models.CharField(blank=True, max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('people_accomodation_capacity', models.IntegerField(default=10)),
                ('no_of_helpers', models.IntegerField(default=4)),
                ('safety_status', models.BooleanField(default=True)),
                ('is_parking_available', models.BooleanField(default=False)),
                ('is_already_online', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.Organization')),
                ('popularity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Popularity')),
            ],
            options={
                'verbose_name_plural': 'StoreDetails',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chandigarh'), ('CG', 'Chhattisgarh'), ('DH', 'Dadra and Nagar Haveli'), ('CG', 'Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Orissa'), ('PY', 'Pondicherry'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TR', 'Tripura'), ('UK', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal')], max_length=25)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('latitude', models.CharField(default='26.8467° N', max_length=20)),
                ('longitude', models.CharField(default='80.9462° E', max_length=20)),
                ('owner_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('img_path', models.CharField(max_length=50)),
                ('storeimage', models.ImageField(blank=True, upload_to='images/store')),
                ('store_category', models.ManyToManyField(to='stores.StoreCategory')),
                ('store_details', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.StoreDetails')),
                ('store_manager', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.SET_DEFAULT, to='stores.StoreManager')),
                ('store_subcategory', models.ManyToManyField(to='stores.StoreSubcategory')),
            ],
        ),
    ]
