# Generated by Django 3.0.8 on 2020-10-31 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201029_1758'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='store',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Seller'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='img_path',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
