# Generated by Django 3.0.8 on 2020-11-01 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20201101_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_manager',
        ),
    ]
