# Generated by Django 3.0.8 on 2020-11-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_remove_store_store_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_manager',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='stores.StoreManager'),
        ),
    ]
