# Generated by Django 3.0.8 on 2020-11-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_store_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_details',
        ),
        migrations.AddField(
            model_name='storedetails',
            name='store',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.Store'),
            preserve_default=False,
        ),
    ]
