# Generated by Django 3.1.2 on 2020-12-01 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201121_1545'),
        ('stores', '0006_auto_20201101_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.seller'),
            preserve_default=False,
        ),
    ]
