# Generated by Django 3.1.2 on 2020-12-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_organization_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='storeimage',
            field=models.ImageField(blank=True, upload_to='images/store', verbose_name='Image'),
        ),
    ]
