# Generated by Django 3.1.2 on 2020-12-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_auto_20201217_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'ProductCategories',
            },
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_subcategory',
        ),
        migrations.AddField(
            model_name='store',
            name='product_category',
            field=models.ManyToManyField(to='stores.ProductCategory'),
        ),
    ]
