# Generated by Django 3.0.8 on 2021-02-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_auto_20210204_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.CharField(blank=True, default='26.8467° N', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.CharField(blank=True, default='80.9462° E', max_length=20, null=True),
        ),
    ]
