# Generated by Django 3.1.2 on 2021-02-16 12:47

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_auto_20210204_0906'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='qrcode_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='store',
            field=models.ManyToManyField(to='stores.Store'),
        ),
        migrations.CreateModel(
            name='GarmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('primary_color', models.CharField(max_length=30)),
                ('other_colors', models.CharField(max_length=150)),
                ('material', models.CharField(max_length=100)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('quantity_unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Dozen', 'Dozen'), ('Kg', 'Kilogram'), ('L', 'Litre'), ('G', 'Gram'), ('M', 'Metre')], default='Pieces', max_length=20)),
                ('colors_available', models.CharField(blank=True, max_length=200, null=True)),
                ('pockets_qty', models.IntegerField(blank=True, default=1)),
                ('description', models.TextField(blank=True)),
                ('neck_design', models.CharField(choices=[('Round', 'Round'), ('V-neck', 'V-neck'), ('PoloCollar', 'PoloCollar'), ('NA', 'Not Applicable')], default='Round', max_length=20)),
                ('design_pattern', multiselectfield.db.fields.MultiSelectField(choices=[('Checks', 'Checks'), ('Floral', 'Floral'), ('Stripes', 'Stripes'), ('Plain', 'Plain'), ('Prints', 'Prints'), ('Dots', 'Dots'), ('Logos', 'Logos'), ('Slogans', 'Slogans'), ('Others', 'Others')], max_length=60)),
                ('sizes_available', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=17)),
                ('garment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.garment')),
            ],
            options={
                'verbose_name_plural': 'GarmentDetails',
                'abstract': False,
            },
        ),
    ]
