# Generated by Django 3.1.2 on 2021-01-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_auto_20210131_1239'),
        ('products', '0001_initial'),
    ]

    operations = [      
        migrations.RemoveField(
            model_name='garment',
            name='store',
            field=models.ManyToManyField(to='stores.Store'),
        ),
    ]
