# Generated by Django 3.1.2 on 2021-02-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_garmentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garmentdetails',
            name='specific_name',
        ),
        migrations.AddField(
            model_name='garmentdetails',
            name='colors_available',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
