# Generated by Django 3.1.2 on 2021-02-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210204_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='qrcode_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
