# Generated by Django 3.1.2 on 2021-02-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_garment_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmentdetails',
            name='quantity_unit',
            field=models.CharField(choices=[('Pieces', 'Pieces'), ('Dozen', 'Dozen'), ('Kg', 'Kilogram'), ('L', 'Litre'), ('G', 'Gram'), ('M', 'Metre')], default='Pieces', max_length=20),
        ),
    ]
