# Generated by Django 3.1.2 on 2021-02-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_garmentdetails_quantity_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garmentdetails',
            old_name='colors',
            new_name='other_colors',
        ),
        migrations.AddField(
            model_name='garmentdetails',
            name='primary_color',
            field=models.CharField(default='White', max_length=30),
            preserve_default=False,
        ),
    ]
